import { NFTData } from './types';

export const GOODLUMS_NFT_DATA: NFTData[] = [
  {
    id: 1,
    tokenId: '1',
    name: 'GOODLUM #1',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%231',
    rarity: 'legendary',
    rarityRank: 7,
    rarityScore: 487.3,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'ORIGINAL GANGSTERS', rarity_percentage: 1.2 },
      { trait_type: 'HOMELAND', value: 'THE WASTELAND', rarity_percentage: 2.4 },
      { trait_type: 'CLOTHING', value: 'TACTICAL HAZMAT', rarity_percentage: 0.8 },
      { trait_type: 'SPECIAL', value: 'DOUBLE HOOD PASS', rarity_percentage: 0.4 },
      { trait_type: 'HOOD PASS', value: 'DIAMOND', rarity_percentage: 1.6 },
    ],
    lastSalePrice: '2.5 ETH',
    currentPrice: '3.2 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/1',
  },
  {
    id: 2,
    tokenId: '2',
    name: 'GOODLUM #2',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%232',
    rarity: 'legendary',
    rarityRank: 3,
    rarityScore: 521.7,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SHADOW COLLECTIVE', rarity_percentage: 1.8 },
      { trait_type: 'HOMELAND', value: 'SIGNAL TOWERS', rarity_percentage: 3.1 },
      { trait_type: 'CLOTHING', value: 'SIGNAL CLOAK', rarity_percentage: 1.2 },
      { trait_type: 'SPECIAL', value: 'NEON VISION', rarity_percentage: 0.6 },
      { trait_type: 'HOOD PASS', value: 'DIAMOND', rarity_percentage: 1.6 },
    ],
    lastSalePrice: '3.8 ETH',
    currentPrice: '4.5 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/2',
  },
  {
    id: 3,
    tokenId: '3',
    name: 'GOODLUM #3',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%233',
    rarity: 'legendary',
    rarityRank: 1,
    rarityScore: 612.4,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'NEON SYNDICATE', rarity_percentage: 2.0 },
      { trait_type: 'HOMELAND', value: 'NEON DISTRICT', rarity_percentage: 2.8 },
      { trait_type: 'CLOTHING', value: 'NEON JACKET', rarity_percentage: 1.4 },
      { trait_type: 'SPECIAL', value: 'GLITCH POWER', rarity_percentage: 0.2 },
      { trait_type: 'HOOD PASS', value: 'DIAMOND', rarity_percentage: 1.6 },
    ],
    lastSalePrice: '5.0 ETH',
    currentPrice: '6.2 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/3',
  },
  {
    id: 4,
    tokenId: '4',
    name: 'GOODLUM #4',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%234',
    rarity: 'epic',
    rarityRank: 12,
    rarityScore: 398.1,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'RUST BROTHERHOOD', rarity_percentage: 3.2 },
      { trait_type: 'HOMELAND', value: 'RUST BELT', rarity_percentage: 4.5 },
      { trait_type: 'CLOTHING', value: 'RUST ARMOR', rarity_percentage: 2.1 },
      { trait_type: 'SPECIAL', value: 'RUST IMMUNITY', rarity_percentage: 1.8 },
      { trait_type: 'HOOD PASS', value: 'GOLD', rarity_percentage: 4.2 },
    ],
    lastSalePrice: '1.2 ETH',
    currentPrice: '1.8 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/4',
  },
  {
    id: 5,
    tokenId: '5',
    name: 'GOODLUM #5',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%235',
    rarity: 'epic',
    rarityRank: 18,
    rarityScore: 356.9,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'STATIC QUEENS', rarity_percentage: 2.6 },
      { trait_type: 'HOMELAND', value: 'THE GRID', rarity_percentage: 5.2 },
      { trait_type: 'CLOTHING', value: 'STATIC COAT', rarity_percentage: 2.8 },
      { trait_type: 'SPECIAL', value: 'STATIC SHIELD', rarity_percentage: 2.2 },
      { trait_type: 'HOOD PASS', value: 'GOLD', rarity_percentage: 4.2 },
    ],
    lastSalePrice: '0.9 ETH',
    currentPrice: '1.4 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/5',
  },
  {
    id: 6,
    tokenId: '6',
    name: 'GOODLUM #6',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%236',
    rarity: 'epic',
    rarityRank: 24,
    rarityScore: 334.2,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'DECAY FACTION', rarity_percentage: 4.1 },
      { trait_type: 'HOMELAND', value: 'SHADOW ZONE', rarity_percentage: 6.0 },
      { trait_type: 'CLOTHING', value: 'DECAY VEST', rarity_percentage: 3.4 },
      { trait_type: 'SPECIAL', value: 'DECAY AURA', rarity_percentage: 2.6 },
      { trait_type: 'HOOD PASS', value: 'GOLD', rarity_percentage: 4.2 },
    ],
    lastSalePrice: '0.75 ETH',
    currentPrice: '1.1 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/6',
  },
  {
    id: 7,
    tokenId: '7',
    name: 'GOODLUM #7',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%237',
    rarity: 'epic',
    rarityRank: 31,
    rarityScore: 312.8,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SIGNAL CORP', rarity_percentage: 3.8 },
      { trait_type: 'HOMELAND', value: 'DEAD CITY', rarity_percentage: 5.6 },
      { trait_type: 'CLOTHING', value: 'GLITCH HOODIE', rarity_percentage: 2.9 },
      { trait_type: 'SPECIAL', value: 'SIGNAL BOOST', rarity_percentage: 3.1 },
      { trait_type: 'HOOD PASS', value: 'GOLD', rarity_percentage: 4.2 },
    ],
    lastSalePrice: '0.65 ETH',
    currentPrice: '0.95 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/7',
  },
  {
    id: 8,
    tokenId: '8',
    name: 'GOODLUM #8',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%238',
    rarity: 'epic',
    rarityRank: 38,
    rarityScore: 298.4,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'ORIGINAL GANGSTERS', rarity_percentage: 1.2 },
      { trait_type: 'HOMELAND', value: 'THE WASTELAND', rarity_percentage: 2.4 },
      { trait_type: 'CLOTHING', value: 'TACTICAL HAZMAT', rarity_percentage: 0.8 },
      { trait_type: 'SPECIAL', value: 'GLITCH POWER', rarity_percentage: 1.4 },
      { trait_type: 'HOOD PASS', value: 'SILVER', rarity_percentage: 8.6 },
    ],
    lastSalePrice: '0.55 ETH',
    currentPrice: '0.82 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/8',
  },
  {
    id: 9,
    tokenId: '9',
    name: 'GOODLUM #9',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%239',
    rarity: 'rare',
    rarityRank: 52,
    rarityScore: 245.6,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SHADOW COLLECTIVE', rarity_percentage: 1.8 },
      { trait_type: 'HOMELAND', value: 'SIGNAL TOWERS', rarity_percentage: 3.1 },
      { trait_type: 'CLOTHING', value: 'NEON JACKET', rarity_percentage: 4.2 },
      { trait_type: 'SPECIAL', value: 'NEON VISION', rarity_percentage: 5.1 },
      { trait_type: 'HOOD PASS', value: 'SILVER', rarity_percentage: 8.6 },
    ],
    lastSalePrice: '0.35 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/9',
  },
  {
    id: 10,
    tokenId: '10',
    name: 'GOODLUM #10',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2310',
    rarity: 'rare',
    rarityRank: 67,
    rarityScore: 228.3,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'NEON SYNDICATE', rarity_percentage: 2.0 },
      { trait_type: 'HOMELAND', value: 'NEON DISTRICT', rarity_percentage: 2.8 },
      { trait_type: 'CLOTHING', value: 'SIGNAL CLOAK', rarity_percentage: 4.8 },
      { trait_type: 'SPECIAL', value: 'STATIC SHIELD', rarity_percentage: 5.4 },
      { trait_type: 'HOOD PASS', value: 'SILVER', rarity_percentage: 8.6 },
    ],
    lastSalePrice: '0.28 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/10',
  },
  {
    id: 11,
    tokenId: '11',
    name: 'GOODLUM #11',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2311',
    rarity: 'rare',
    rarityRank: 78,
    rarityScore: 215.7,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'RUST BROTHERHOOD', rarity_percentage: 3.2 },
      { trait_type: 'HOMELAND', value: 'RUST BELT', rarity_percentage: 4.5 },
      { trait_type: 'CLOTHING', value: 'RUST ARMOR', rarity_percentage: 3.8 },
      { trait_type: 'SPECIAL', value: 'RUST IMMUNITY', rarity_percentage: 4.6 },
      { trait_type: 'HOOD PASS', value: 'BRONZE', rarity_percentage: 14.2 },
    ],
    lastSalePrice: '0.22 ETH',
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/11',
  },
  {
    id: 12,
    tokenId: '12',
    name: 'GOODLUM #12',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2312',
    rarity: 'rare',
    rarityRank: 89,
    rarityScore: 201.4,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'STATIC QUEENS', rarity_percentage: 2.6 },
      { trait_type: 'HOMELAND', value: 'THE GRID', rarity_percentage: 5.2 },
      { trait_type: 'CLOTHING', value: 'STATIC COAT', rarity_percentage: 5.1 },
      { trait_type: 'SPECIAL', value: 'DECAY AURA', rarity_percentage: 5.8 },
      { trait_type: 'HOOD PASS', value: 'BRONZE', rarity_percentage: 14.2 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/12',
  },
  {
    id: 13,
    tokenId: '13',
    name: 'GOODLUM #13',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2313',
    rarity: 'rare',
    rarityRank: 102,
    rarityScore: 188.9,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'DECAY FACTION', rarity_percentage: 4.1 },
      { trait_type: 'HOMELAND', value: 'SHADOW ZONE', rarity_percentage: 6.0 },
      { trait_type: 'CLOTHING', value: 'DECAY VEST', rarity_percentage: 5.6 },
      { trait_type: 'SPECIAL', value: 'SIGNAL BOOST', rarity_percentage: 6.2 },
      { trait_type: 'HOOD PASS', value: 'BRONZE', rarity_percentage: 14.2 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/13',
  },
  {
    id: 14,
    tokenId: '14',
    name: 'GOODLUM #14',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2314',
    rarity: 'rare',
    rarityRank: 118,
    rarityScore: 175.2,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SIGNAL CORP', rarity_percentage: 3.8 },
      { trait_type: 'HOMELAND', value: 'DEAD CITY', rarity_percentage: 5.6 },
      { trait_type: 'CLOTHING', value: 'GLITCH HOODIE', rarity_percentage: 4.4 },
      { trait_type: 'SPECIAL', value: 'DOUBLE HOOD PASS', rarity_percentage: 3.8 },
      { trait_type: 'HOOD PASS', value: 'BRONZE', rarity_percentage: 14.2 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/14',
  },
  {
    id: 15,
    tokenId: '15',
    name: 'GOODLUM #15',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2315',
    rarity: 'rare',
    rarityRank: 131,
    rarityScore: 162.8,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'ORIGINAL GANGSTERS', rarity_percentage: 1.2 },
      { trait_type: 'HOMELAND', value: 'THE WASTELAND', rarity_percentage: 2.4 },
      { trait_type: 'CLOTHING', value: 'TACTICAL HAZMAT', rarity_percentage: 0.8 },
      { trait_type: 'SPECIAL', value: 'NEON VISION', rarity_percentage: 5.1 },
      { trait_type: 'HOOD PASS', value: 'BRONZE', rarity_percentage: 14.2 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/15',
  },
  {
    id: 16,
    tokenId: '16',
    name: 'GOODLUM #16',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2316',
    rarity: 'rare',
    rarityRank: 144,
    rarityScore: 152.1,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SHADOW COLLECTIVE', rarity_percentage: 1.8 },
      { trait_type: 'HOMELAND', value: 'NEON DISTRICT', rarity_percentage: 2.8 },
      { trait_type: 'CLOTHING', value: 'NEON JACKET', rarity_percentage: 4.2 },
      { trait_type: 'SPECIAL', value: 'GLITCH POWER', rarity_percentage: 4.8 },
      { trait_type: 'HOOD PASS', value: 'SILVER', rarity_percentage: 8.6 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/16',
  },
  {
    id: 17,
    tokenId: '17',
    name: 'GOODLUM #17',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2317',
    rarity: 'rare',
    rarityRank: 156,
    rarityScore: 143.5,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'NEON SYNDICATE', rarity_percentage: 2.0 },
      { trait_type: 'HOMELAND', value: 'SIGNAL TOWERS', rarity_percentage: 3.1 },
      { trait_type: 'CLOTHING', value: 'RUST ARMOR', rarity_percentage: 3.8 },
      { trait_type: 'SPECIAL', value: 'STATIC SHIELD', rarity_percentage: 5.4 },
      { trait_type: 'HOOD PASS', value: 'SILVER', rarity_percentage: 8.6 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/17',
  },
  {
    id: 18,
    tokenId: '18',
    name: 'GOODLUM #18',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2318',
    rarity: 'rare',
    rarityRank: 148,
    rarityScore: 149.2,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'RUST BROTHERHOOD', rarity_percentage: 3.2 },
      { trait_type: 'HOMELAND', value: 'RUST BELT', rarity_percentage: 4.5 },
      { trait_type: 'CLOTHING', value: 'SIGNAL CLOAK', rarity_percentage: 4.8 },
      { trait_type: 'SPECIAL', value: 'RUST IMMUNITY', rarity_percentage: 4.6 },
      { trait_type: 'HOOD PASS', value: 'SILVER', rarity_percentage: 8.6 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/18',
  },
  {
    id: 19,
    tokenId: '19',
    name: 'GOODLUM #19',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2319',
    rarity: 'common',
    rarityRank: 182,
    rarityScore: 118.6,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'STATIC QUEENS', rarity_percentage: 2.6 },
      { trait_type: 'HOMELAND', value: 'DEAD CITY', rarity_percentage: 5.6 },
      { trait_type: 'CLOTHING', value: 'STATIC COAT', rarity_percentage: 5.1 },
      { trait_type: 'SPECIAL', value: 'DECAY AURA', rarity_percentage: 5.8 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/19',
  },
  {
    id: 20,
    tokenId: '20',
    name: 'GOODLUM #20',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2320',
    rarity: 'common',
    rarityRank: 201,
    rarityScore: 107.4,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'DECAY FACTION', rarity_percentage: 4.1 },
      { trait_type: 'HOMELAND', value: 'THE GRID', rarity_percentage: 5.2 },
      { trait_type: 'CLOTHING', value: 'DECAY VEST', rarity_percentage: 5.6 },
      { trait_type: 'SPECIAL', value: 'SIGNAL BOOST', rarity_percentage: 6.2 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/20',
  },
  {
    id: 21,
    tokenId: '21',
    name: 'GOODLUM #21',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2321',
    rarity: 'common',
    rarityRank: 224,
    rarityScore: 96.2,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SIGNAL CORP', rarity_percentage: 3.8 },
      { trait_type: 'HOMELAND', value: 'SHADOW ZONE', rarity_percentage: 6.0 },
      { trait_type: 'CLOTHING', value: 'GLITCH HOODIE', rarity_percentage: 4.4 },
      { trait_type: 'SPECIAL', value: 'DOUBLE HOOD PASS', rarity_percentage: 3.8 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/21',
  },
  {
    id: 22,
    tokenId: '22',
    name: 'GOODLUM #22',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2322',
    rarity: 'common',
    rarityRank: 247,
    rarityScore: 88.1,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'ORIGINAL GANGSTERS', rarity_percentage: 1.2 },
      { trait_type: 'HOMELAND', value: 'THE WASTELAND', rarity_percentage: 2.4 },
      { trait_type: 'CLOTHING', value: 'TACTICAL HAZMAT', rarity_percentage: 0.8 },
      { trait_type: 'SPECIAL', value: 'NEON VISION', rarity_percentage: 5.1 },
      { trait_type: 'HOOD PASS', value: 'BRONZE', rarity_percentage: 14.2 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/22',
  },
  {
    id: 23,
    tokenId: '23',
    name: 'GOODLUM #23',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2323',
    rarity: 'common',
    rarityRank: 268,
    rarityScore: 81.4,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SHADOW COLLECTIVE', rarity_percentage: 1.8 },
      { trait_type: 'HOMELAND', value: 'DEAD CITY', rarity_percentage: 5.6 },
      { trait_type: 'CLOTHING', value: 'NEON JACKET', rarity_percentage: 4.2 },
      { trait_type: 'SPECIAL', value: 'GLITCH POWER', rarity_percentage: 4.8 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/23',
  },
  {
    id: 24,
    tokenId: '24',
    name: 'GOODLUM #24',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2324',
    rarity: 'common',
    rarityRank: 289,
    rarityScore: 74.8,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'NEON SYNDICATE', rarity_percentage: 2.0 },
      { trait_type: 'HOMELAND', value: 'NEON DISTRICT', rarity_percentage: 2.8 },
      { trait_type: 'CLOTHING', value: 'SIGNAL CLOAK', rarity_percentage: 4.8 },
      { trait_type: 'SPECIAL', value: 'STATIC SHIELD', rarity_percentage: 5.4 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/24',
  },
  {
    id: 25,
    tokenId: '25',
    name: 'GOODLUM #25',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2325',
    rarity: 'common',
    rarityRank: 312,
    rarityScore: 68.3,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'RUST BROTHERHOOD', rarity_percentage: 3.2 },
      { trait_type: 'HOMELAND', value: 'RUST BELT', rarity_percentage: 4.5 },
      { trait_type: 'CLOTHING', value: 'RUST ARMOR', rarity_percentage: 3.8 },
      { trait_type: 'SPECIAL', value: 'RUST IMMUNITY', rarity_percentage: 4.6 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/25',
  },
  {
    id: 26,
    tokenId: '26',
    name: 'GOODLUM #26',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2326',
    rarity: 'common',
    rarityRank: 335,
    rarityScore: 61.7,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'STATIC QUEENS', rarity_percentage: 2.6 },
      { trait_type: 'HOMELAND', value: 'THE GRID', rarity_percentage: 5.2 },
      { trait_type: 'CLOTHING', value: 'STATIC COAT', rarity_percentage: 5.1 },
      { trait_type: 'SPECIAL', value: 'DECAY AURA', rarity_percentage: 5.8 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/26',
  },
  {
    id: 27,
    tokenId: '27',
    name: 'GOODLUM #27',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2327',
    rarity: 'common',
    rarityRank: 358,
    rarityScore: 55.2,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'DECAY FACTION', rarity_percentage: 4.1 },
      { trait_type: 'HOMELAND', value: 'SHADOW ZONE', rarity_percentage: 6.0 },
      { trait_type: 'CLOTHING', value: 'DECAY VEST', rarity_percentage: 5.6 },
      { trait_type: 'SPECIAL', value: 'SIGNAL BOOST', rarity_percentage: 6.2 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/27',
  },
  {
    id: 28,
    tokenId: '28',
    name: 'GOODLUM #28',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2328',
    rarity: 'common',
    rarityRank: 381,
    rarityScore: 49.6,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SIGNAL CORP', rarity_percentage: 3.8 },
      { trait_type: 'HOMELAND', value: 'DEAD CITY', rarity_percentage: 5.6 },
      { trait_type: 'CLOTHING', value: 'GLITCH HOODIE', rarity_percentage: 4.4 },
      { trait_type: 'SPECIAL', value: 'DOUBLE HOOD PASS', rarity_percentage: 3.8 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/28',
  },
  {
    id: 29,
    tokenId: '29',
    name: 'GOODLUM #29',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2329',
    rarity: 'common',
    rarityRank: 404,
    rarityScore: 43.1,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'ORIGINAL GANGSTERS', rarity_percentage: 1.2 },
      { trait_type: 'HOMELAND', value: 'SIGNAL TOWERS', rarity_percentage: 3.1 },
      { trait_type: 'CLOTHING', value: 'TACTICAL HAZMAT', rarity_percentage: 0.8 },
      { trait_type: 'SPECIAL', value: 'GLITCH POWER', rarity_percentage: 4.8 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/29',
  },
  {
    id: 30,
    tokenId: '30',
    name: 'GOODLUM #30',
    image: 'https://via.placeholder.com/400x400/0a0a0a/0f0?text=GOODLUM+%2330',
    rarity: 'common',
    rarityRank: 427,
    rarityScore: 37.4,
    traits: [
      { trait_type: 'GANG AFFILIATION', value: 'SHADOW COLLECTIVE', rarity_percentage: 1.8 },
      { trait_type: 'HOMELAND', value: 'THE WASTELAND', rarity_percentage: 2.4 },
      { trait_type: 'CLOTHING', value: 'NEON JACKET', rarity_percentage: 4.2 },
      { trait_type: 'SPECIAL', value: 'NEON VISION', rarity_percentage: 5.1 },
      { trait_type: 'HOOD PASS', value: 'NONE', rarity_percentage: 42.8 },
    ],
    openseaUrl: 'https://opensea.io/assets/base/0x1234567890abcdef/30',
  },
];

export const TOTAL_SUPPLY = 500;
